server:
  port: 7888
spring:
  application:
    name: service-stream
  cloud:
    stream:
      kafka:
        #Kafka的消息中间件服务器
        brokers:
          localhost: 9092
        #Zookeeper的节点，如果集群，后面加,号分隔
        zk-nodes:
          localhost: 2181
        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
        auto-create-topics: true
      bindings:
      #这里用stream给我们提供的默认output，后面会讲到自定义output
        myOutput:
        #消息发往的目的地
          destination: stream-demo
          #消息发送的格式，接收端不用指定格式，但是发送端要
          content-type: text/plain
          producer:
            #分区的主键，根据什么来区分，payload.id只是一个对象的id作为key，用于说明
            partitionKeyExpression: payload
            #key和分区数量进行取模去分配消息，分区数为2
            partitionCount: 2