server:
  port: 8763

eureka:
  instance:
    hostname: localhost
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.1.54:8761/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: all-eureka-client
