server:
  port: 7890
spring:
  application:
    name: service-stream2
  cloud:
    stream:
      kafka:
        #Kafka的消息中间件服务器
        brokers:
          localhost: 9092
        #Zookeeper的节点，如果集群，后面加,号分隔
        zk-nodes:
          localhost: 2181
        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
        auto-create-topics: true
      bindings:
      #这里用stream给我们提供的默认output，后面会讲到自定义output
        input:
        #消息发往的目的地
          destination: stream-demo-trans
          group: group
          consumer:
            #开启消息分区
            partitioned: true
            #分区数量 当前消息者的总的实例个数
            instance-count: 2
            #当前实例的索引，从0开始，当我们启动多个实例时，需要在启动时在命令行配置索引
            instance-index: 0
