server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.54:8761/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: all-eureka-server
  sleuth:
    sampler:
      probability: 1.0