server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: all-eureka-server
  sleuth:
    sampler:
      probability: 1.0